services:
  vault:
    image: hashicorp/vault:1.17.2
    restart: always
    volumes:
      - vault-logs:/vault/logs/:rw
      - vault-data:/vault/data/:rw
      - ./plugin:/vault/plugin/:rw
      - ./config:/vault/config/:rw
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config /vault/config/config.hcl
  gateway:
    image: nghnhhquang/ranger-gateway:latest
    depends_on:
      - redis
      - ranger
      - vault
    environment:
      - TZ=Asia/Jakarta
      - ASPNETCORE_ENVIRONMENT=poc
    extra_hosts:
      - "vault.hanas.io:192.168.128.41"
      - "dataiku:192.168.121.41"
      - "confluent:192.168.121.42"
      - "jbpm:192.168.128.41"
      - "workflow:192.168.128.41"
      - "autovault:192.168.128.41"
      - "chatbot:192.168.128.41"
      - "erd:192.168.128.41"
    networks:
      default:
      datahub_network:
    external_links:
      - datahub-datahub-frontend-react-1:datahub
  ranger:
    image: nghnhhquang/ranger-admin:latest
    depends_on:
      ranger-zk:
        condition: service_started
      ranger-db:
        condition: service_healthy
      ranger-solr:
        condition: service_started      
    environment:
      - TZ=Asia/Jakarta
  nginx:
    image: nginx:alpine
    ports:
      - 443:443
      - 8080:8080
      - 11000:11000
      - 9002:9002
      - 5001:5001
      - 8200:8200
      - 9021:9021
    extra_hosts:
      - "dataiku:192.168.121.41"
      - "confluent:192.168.121.42"
      - "jbpm:192.168.128.41"
      - "workflow:192.168.128.41"
      - "autovault:192.168.128.41"
      - "chatbot:192.168.128.41"
      - "erd:192.168.128.41"
    networks:
      default:
      datahub_network:
    external_links:
      - datahub-datahub-frontend-react-1:datahub
    depends_on:
      - gateway
      - ranger
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
  ranger-db:
    image: nghnhhquang/ranger-postgres:latest
    healthcheck:
      test: 'su -c "pg_isready -q" postgres'
      interval: 10s
      timeout: 2s
      retries: 30
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - postgres-data:/var/lib/postgresql/data
  ranger-zk:
    image: nghnhhquang/ranger-zk:latest
    environment:
      - TZ=Asia/Jakarta
  ranger-solr:
    image: nghnhhquang/ranger-solr:latest
    command:
      - solr-precreate
      - ranger_audits
      - /opt/solr/server/solr/configsets/ranger_audits/
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - solr-data:/var/solr/data/
  redis:
    image: redis
volumes:
  postgres-data:
  solr-data:
  vault-logs:
  vault-data:
networks:
  default:
    name: hanas-poc_default
  datahub_network:
    external: true
    name: datahub_network