services:
  redis:
    image: redis
  rhpam-iafs:
    image: nghnhhquang/pam-portal-iafs
    restart: always
    ports:
    - 5001:5001
    depends_on:
    - redis
    volumes:
    - ./rhpam-iafs.json:/app/appsettings.json
    - ./rhpam-iafs.json:/app/appsettings.Development.json
    - rhpam-log-data:/app/LogFile
    - rhpam-migrations:/app/Migrations
  rhpam-iafs-api:
    image: nghnhhquang/pam-portal-iafs-api
    restart: always
    ports:
    - 5011:5011
    depends_on:
    - redis
    volumes:
    - ./rhpam-iafs-api.json:/app/appsettings.json
    - ./rhpam-iafs-api.json:/app/appsettings.Development.json
  iafs-maths-engine:
    image: nghnhhquang/pam-portal-iafs-engine
    restart: always
    ports:
    - 5002:5002
    depends_on:
    - redis
    volumes:
    - ./iafs-maths-engine.json:/app/appsettings.json
volumes:
  rhpam-log-data:
  rhpam-migrations: