services:
  redis:
    image: redis
  rhpam-iafs:
    image: nghnhhquang/pam-portal
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - 2888:5001
    command: 
    - dotnet
    - run
    - --project
    - ./rhpam-iafs/iafs.csproj
    - --urls
    - http://0.0.0.0:5001
    depends_on:
    - redis
    volumes:
    - ./rhpam-iafs.json:/src/rhpam-iafs/appsettings.Development.json
    - rhpam-log-data:/src/rhpam-iafs/LogFile
  rhpam-iafs-api:
    image: nghnhhquang/pam-portal
    #http://14.241.249.100:7979/katalyst1/shinhan_pam.git
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
    - redis
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    volumes:
    - ./rhpam-iafs-api.json:/src/rhpam-iafs-api/src/rhpam-iafs-api/rhpam-iafs-api/appsettings.Development.json
    command:
    - dotnet
    - run
    - --project
    - ./rhpam-iafs-api/src/rhpam-iafs-api/rhpam-iafs-api.csproj
    - --urls
    - http://0.0.0.0:5011
  iafs-maths-engine:
    image: nghnhhquang/pam-portal
    depends_on:
    - redis
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    volumes:
    - ./iafs-maths-engine.json:/src/iafs-maths-engine/appsettings.Development.json
    command:
    - dotnet
    - run
    - --project
    - ./iafs-maths-engine/iafs-maths-engines.csproj
    - --urls
    - http://0.0.0.0:5002
  postgres:
    image: postgres:9.6
    volumes:
    - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: jbpm
      POSTGRES_USER: jbpm
      POSTGRES_PASSWORD: jbpm
  jbpm:
    image: thongdq3108/jbpm-server-full:latest
    environment:
      JBPM_DB_DRIVER: postgres
      JBPM_DB_HOST: postgres
    ports:
    - 8001:8001
    - 9093:8080
    depends_on:
    - postgres
volumes:
  postgres_data:
  rhpam-log-data: