--------------------------------------------------------
--  File created - Tuesday-September-24-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table Scheduler
--------------------------------------------------------

  CREATE TABLE "Scheduler" 
   (	"Id" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 59 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"Name" NVARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"Type" NUMBER(10,0), 
	"Action" NVARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"AllowMultiTrigger" NUMBER(10,0), 
	"IntervalInSecond" NUMBER(10,0), 
	"NextActionTime" TIMESTAMP (7), 
	"LastActionStatus" NVARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"EnableFrTime" INTERVAL DAY (8) TO SECOND (7) DEFAULT INTERVAL '0 0:0:0.000' DAY TO SECOND, 
	"EnableToTime" INTERVAL DAY (8) TO SECOND (7) DEFAULT INTERVAL '0 0:0:0.000' DAY TO SECOND
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WFL_DATA" ;
REM INSERTING into "Scheduler"
SET DEFINE OFF;
Insert into "Scheduler" ("Id","Name","Type","Action","AllowMultiTrigger","IntervalInSecond","NextActionTime","LastActionStatus","EnableFrTime","EnableToTime") values (57,'Auto Request PAM',6,'http://localhost:5001/AutoService/AutoRunPam',1,120,to_timestamp('24-SEP-24 12.50.00.090495700','DD-MON-RR HH24.MI.SSXFF'),'Finished','+00 01:00:00.000000','+00 20:00:00.000000');
Insert into "Scheduler" ("Id","Name","Type","Action","AllowMultiTrigger","IntervalInSecond","NextActionTime","LastActionStatus","EnableFrTime","EnableToTime") values (53,'Auto Import Excel',6,'http://localhost:5001/AutoService/AutoImportExcel',1,7200,to_timestamp('13-SEP-24 15.40.23.271063100','DD-MON-RR HH24.MI.SSXFF'),'Finished','+00 01:00:00.000000','+00 20:00:00.000000');
Insert into "Scheduler" ("Id","Name","Type","Action","AllowMultiTrigger","IntervalInSecond","NextActionTime","LastActionStatus","EnableFrTime","EnableToTime") values (54,'OCR',6,'http://localhost:5001/AutoService/StartOCR',1,600,to_timestamp('04-MAY-24 11.15.51.442474500','DD-MON-RR HH24.MI.SSXFF'),'Finished','+00 01:00:00.000000','+00 20:00:00.000000');
Insert into "Scheduler" ("Id","Name","Type","Action","AllowMultiTrigger","IntervalInSecond","NextActionTime","LastActionStatus","EnableFrTime","EnableToTime") values (55,'Auto Assign',6,'http://localhost:5001/AutoService/AutoAssign',1,7200,to_timestamp('30-MAY-24 17.47.06.102819000','DD-MON-RR HH24.MI.SSXFF'),'Finished','+00 01:00:00.000000','+00 20:00:00.000000');
Insert into "Scheduler" ("Id","Name","Type","Action","AllowMultiTrigger","IntervalInSecond","NextActionTime","LastActionStatus","EnableFrTime","EnableToTime") values (56,'GC',6,'http://localhost:5001/AutoService/AutoGC',1,600,to_timestamp('14-MAR-24 15.43.46.903356700','DD-MON-RR HH24.MI.SSXFF'),'Finished','+00 11:00:00.000000','+00 19:00:00.000000');
Insert into "Scheduler" ("Id","Name","Type","Action","AllowMultiTrigger","IntervalInSecond","NextActionTime","LastActionStatus","EnableFrTime","EnableToTime") values (58,'Delete dinh ky',6,'http://localhost:5001/AutoService/DeleteUserNotification',1,86400,to_timestamp('25-OCT-23 13.16.00.007756900','DD-MON-RR HH24.MI.SSXFF'),'Finished','+00 01:00:00.000000','+00 20:00:00.000000');
Insert into "Scheduler" ("Id","Name","Type","Action","AllowMultiTrigger","IntervalInSecond","NextActionTime","LastActionStatus","EnableFrTime","EnableToTime") values (62,'Auto Start DeDup',6,'http://localhost:5001/AutoService/AutoStartDedup',1,7200,to_timestamp('23-SEP-24 20.48.13.092131000','DD-MON-RR HH24.MI.SSXFF'),'Finished','+00 01:00:00.000000','+00 20:00:00.000000');
Insert into "Scheduler" ("Id","Name","Type","Action","AllowMultiTrigger","IntervalInSecond","NextActionTime","LastActionStatus","EnableFrTime","EnableToTime") values (61,'Auto Abort',6,'http://localhost:5001/AutoService/AutoAbort',1,7200,to_timestamp('14-SEP-24 10.39.43.588718600','DD-MON-RR HH24.MI.SSXFF'),'Finished','+00 01:00:00.000000','+00 20:00:00.000000');
Insert into "Scheduler" ("Id","Name","Type","Action","AllowMultiTrigger","IntervalInSecond","NextActionTime","LastActionStatus","EnableFrTime","EnableToTime") values (59,'Auto Import FromDB',6,'http://localhost:5001/AutoService/AutoImportFromDB',1,7200,to_timestamp('30-AUG-24 02.02.13.247702100','DD-MON-RR HH24.MI.SSXFF'),'InProcess','+00 01:00:00.000000','+00 20:00:00.000000');
Insert into "Scheduler" ("Id","Name","Type","Action","AllowMultiTrigger","IntervalInSecond","NextActionTime","LastActionStatus","EnableFrTime","EnableToTime") values (60,'Auto Close FromDB',6,'http://localhost:5001/AutoService/AutoCloseFromDB',1,7200,to_timestamp('01-SEP-24 16.02.13.247702100','DD-MON-RR HH24.MI.SSXFF'),'Finished','+00 01:00:00.000000','+00 20:00:00.000000');
--------------------------------------------------------
--  DDL for Index PK_Scheduler
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_Scheduler" ON "Scheduler" ("Id") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WFL_DATA" ;
--------------------------------------------------------
--  Constraints for Table Scheduler
--------------------------------------------------------

  ALTER TABLE "Scheduler" ADD CONSTRAINT "PK_Scheduler" PRIMARY KEY ("Id")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WFL_DATA"  ENABLE;
  ALTER TABLE "Scheduler" MODIFY ("Id" NOT NULL ENABLE);
  ALTER TABLE "Scheduler" MODIFY ("Name" NOT NULL ENABLE);
  ALTER TABLE "Scheduler" MODIFY ("Type" NOT NULL ENABLE);
  ALTER TABLE "Scheduler" MODIFY ("Action" NOT NULL ENABLE);
  ALTER TABLE "Scheduler" MODIFY ("AllowMultiTrigger" NOT NULL ENABLE);
  ALTER TABLE "Scheduler" MODIFY ("IntervalInSecond" NOT NULL ENABLE);
  ALTER TABLE "Scheduler" MODIFY ("NextActionTime" NOT NULL ENABLE);
  ALTER TABLE "Scheduler" MODIFY ("EnableFrTime" NOT NULL ENABLE);
  ALTER TABLE "Scheduler" MODIFY ("EnableToTime" NOT NULL ENABLE);
